name: Report,claim - every 2 hours

on:
  schedule:
    - cron: "0 */2 * * *"

  workflow_dispatch:
    inputs:
      token:
        description: 'secret token'
        required: true

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
    - uses: actions/checkout@master
    
    - name: docker registry login
      run: echo "${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}" | docker login ghcr.io --username admicro --password-stdin
      
    - name: Run report
      if: success()
      run: |
        docker run \
        -e JOB_NAME="report" \
        -e DATABASE_URL="${{  secrets.DATABASE_URL }}" \
        ghcr.io/admicro/ytvid:latest

    - name: Run find claim
      if: success()
      run: |
        docker run \
        -e JOB_NAME="find_claim" \
        -e DATABASE_URL="${{  secrets.DATABASE_URL }}" \
        ghcr.io/admicro/ytvid:latest

    
